messages:
  lock-success: "§bChest locked. Use §a/unlock§b to unlock it and §a/lock + <player1> <player2>...§b to add other players."
  lock-usage: "§a/lock §b[+/- <player1> <player2>...]"
  unlock-success: "§bChest unlocked."
  lock-add-success: "§a{NAME}§b can now use this chest."
  lock-remove-success: "§a{NAME}§b can no longer use this chest."
  error-look-at-chest: "§cYou must look at a chest to use this command."
  error-already-locked: "§cThis chest is already locked."
  error-not-locked: "§cThis chest isn't locked."
  error-not-owner: "§cThis chest doesn't belong to you."
  error-already-has-access: "§6{NAME}§c can already use this chest."
  error-already-has-no-access: "§6{NAME}§c cannot use this chest."
  error-player-does-not-exist: "§cThe player §6{NAME}§c doesn't exist."
  chest-locked: "§bThis chest was locked by §a{NAME}§b."
  chest-nearby-locked: "§cThe chest next to this one is locked."
